/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeekWeekRouteImport } from './routes/week.$week'
import { Route as PosterWeekRouteImport } from './routes/poster.$week'
import { Route as FoodWeekRouteImport } from './routes/food.$week'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekWeekRoute = WeekWeekRouteImport.update({
  id: '/week/$week',
  path: '/week/$week',
  getParentRoute: () => rootRouteImport,
} as any)
const PosterWeekRoute = PosterWeekRouteImport.update({
  id: '/poster/$week',
  path: '/poster/$week',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodWeekRoute = FoodWeekRouteImport.update({
  id: '/food/$week',
  path: '/food/$week',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/food/$week': typeof FoodWeekRoute
  '/poster/$week': typeof PosterWeekRoute
  '/week/$week': typeof WeekWeekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/food/$week': typeof FoodWeekRoute
  '/poster/$week': typeof PosterWeekRoute
  '/week/$week': typeof WeekWeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/food/$week': typeof FoodWeekRoute
  '/poster/$week': typeof PosterWeekRoute
  '/week/$week': typeof WeekWeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/food/$week' | '/poster/$week' | '/week/$week'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/food/$week' | '/poster/$week' | '/week/$week'
  id: '__root__' | '/' | '/food/$week' | '/poster/$week' | '/week/$week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoodWeekRoute: typeof FoodWeekRoute
  PosterWeekRoute: typeof PosterWeekRoute
  WeekWeekRoute: typeof WeekWeekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/week/$week': {
      id: '/week/$week'
      path: '/week/$week'
      fullPath: '/week/$week'
      preLoaderRoute: typeof WeekWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poster/$week': {
      id: '/poster/$week'
      path: '/poster/$week'
      fullPath: '/poster/$week'
      preLoaderRoute: typeof PosterWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/$week': {
      id: '/food/$week'
      path: '/food/$week'
      fullPath: '/food/$week'
      preLoaderRoute: typeof FoodWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoodWeekRoute: FoodWeekRoute,
  PosterWeekRoute: PosterWeekRoute,
  WeekWeekRoute: WeekWeekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
